services:
  db:
    container_name: ServiceFinder.db  
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Replace with a strong password
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"  # Expose SQL Server port
    volumes:
      - db-data:/var/opt/mssql  # Persist SQL data between restarts

volumes:
  db-data: